dwa_planner:
  ros__parameters:
    HZ: 20.0
    PREDICT_TIME: 2.0

    VELOCITY_RESOLUTION: 0.05
    YAWRATE_RESOLUTION: 0.1

    TO_GOAL_COST_GAIN: 1.0
    SPEED_COST_GAIN: 1.0
    OBSTACLE_COST_GAIN: 1.0

    TEMP_GOAL_RADIUS: 1.5
    GOAL_THRESHOLD: 0.2

    ROBOT_FRAME: "base_link"
    MAX_VELOCITY: 0.6
    MIN_VELOCITY: 0.0
    MAX_YAWRATE: 1.0
    MAX_ACCELERATION: 0.5
    MAX_D_YAWRATE: 2.0
    MAX_DIST: 5.0
    ROBOT_RADIUS: 0.3
    SAFETY_MARGIN: 0.1
    LASER_MAX_RANGE: 3.0

    cruise_num: 5
    first_point_x: 1.22
    first_point_y: 5.32
    second_point_x: 5.77
    second_point_y: 5.39
    third_point_x: 6.14
    third_point_y: -1.14
    forth_point_x: -29.00
    forth_point_y: -11.01
    fifth_point_x: -29.66
    fifth_point_y: 20.43