<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>keyboard_control</name>
  <version>0.0.0</version>
  <description>Keyboard control package for differential drive robot in ROS 2</description>
  
  <maintainer email="cfl@todo.todo">cfl</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>